//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lextm.SharpSnmpLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lextm.SharpSnmpLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #SNMPV2-SMI,
        ///.
        /// </summary>
        internal static string SNMPv2_CONF {
            get {
                return ResourceManager.GetString("SNMPv2_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #SNMPV2-SMI,SNMPV2-TC,SNMPV2-CONF,
        ///.1.3.6.1.6.3.1,Lextm.SharpSnmpLib.Mib.ModuleIdentity,snmpMIB,snmpModules
        ///.1.3.6.1.6.3.1.1,Lextm.SharpSnmpLib.Mib.OidValueAssignment,snmpMIBObjects,snmpMIB
        ///.1.3.6.1.2.1.1,Lextm.SharpSnmpLib.Mib.OidValueAssignment,system,mib-2
        ///.1.3.6.1.2.1.1.1,Lextm.SharpSnmpLib.Mib.ObjectType,sysDescr,system
        ///.1.3.6.1.2.1.1.2,Lextm.SharpSnmpLib.Mib.ObjectType,sysObjectID,system
        ///.1.3.6.1.2.1.1.3,Lextm.SharpSnmpLib.Mib.ObjectType,sysUpTime,system
        ///.1.3.6.1.2.1.1.4,Lextm.SharpSnmpLib.Mib. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNMPv2_MIB {
            get {
                return ResourceManager.GetString("SNMPv2_MIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///.1.3,Lextm.SharpSnmpLib.Mib.OidValueAssignment,org,iso
        ///.1.3.6,Lextm.SharpSnmpLib.Mib.OidValueAssignment,dod,org
        ///.1.3.6.1,Lextm.SharpSnmpLib.Mib.OidValueAssignment,internet,dod
        ///.1.3.6.1.1,Lextm.SharpSnmpLib.Mib.OidValueAssignment,directory,internet
        ///.1.3.6.1.2,Lextm.SharpSnmpLib.Mib.OidValueAssignment,mgmt,internet
        ///.1.3.6.1.2.1,Lextm.SharpSnmpLib.Mib.OidValueAssignment,mib-2,mgmt
        ///.1.3.6.1.2.1.10,Lextm.SharpSnmpLib.Mib.OidValueAssignment,transmission,mib-2
        ///.1.3.6.1.3,Lextm.SharpSnmpLib.Mib.OidValueAs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNMPv2_SMI {
            get {
                return ResourceManager.GetString("SNMPv2_SMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #SNMPV2-SMI,
        ///.
        /// </summary>
        internal static string SNMPv2_TC {
            get {
                return ResourceManager.GetString("SNMPv2_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #SNMPV2-SMI,SNMPV2-TC,
        ///.1.3.6.1.6.3.19,Lextm.SharpSnmpLib.Mib.ModuleIdentity,snmpv2tm,snmpModules
        ///.1.3.6.1.6.1.1,Lextm.SharpSnmpLib.Mib.ObjectIdentity,snmpUDPDomain,snmpDomains
        ///.1.3.6.1.6.1.2,Lextm.SharpSnmpLib.Mib.ObjectIdentity,snmpCLNSDomain,snmpDomains
        ///.1.3.6.1.6.1.3,Lextm.SharpSnmpLib.Mib.ObjectIdentity,snmpCONSDomain,snmpDomains
        ///.1.3.6.1.6.1.4,Lextm.SharpSnmpLib.Mib.ObjectIdentity,snmpDDPDomain,snmpDomains
        ///.1.3.6.1.6.1.5,Lextm.SharpSnmpLib.Mib.ObjectIdentity,snmpIPXDomain,snmpDomains
        ///.1.3.6.1.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNMPv2_TM {
            get {
                return ResourceManager.GetString("SNMPv2_TM", resourceCulture);
            }
        }
    }
}
