//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lextm.SharpSnmpLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lextm.SharpSnmpLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ACTONA_ACTASTOR_MIB {
            get {
                object obj = ResourceManager.GetObject("ACTONA-ACTASTOR-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ADSL_LINE_MIB {
            get {
                object obj = ResourceManager.GetObject("ADSL-LINE-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ADSL_TC_MIB {
            get {
                object obj = ResourceManager.GetObject("ADSL-TC-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AGENTX_MIB {
            get {
                object obj = ResourceManager.GetObject("AGENTX-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AIRPORT_BASESTATION_3_MIB {
            get {
                object obj = ResourceManager.GetObject("AIRPORT-BASESTATION-3-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ALLIEDTELESYN_MIB {
            get {
                object obj = ResourceManager.GetObject("ALLIEDTELESYN-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ALVARION_DOT11_WLAN_MIB {
            get {
                object obj = ResourceManager.GetObject("ALVARION-DOT11-WLAN-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] APPC_MIB {
            get {
                object obj = ResourceManager.GetObject("APPC-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARRAYMANAGER_MIB {
            get {
                object obj = ResourceManager.GetObject("ARRAYMANAGER-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARROWPOINT_IPV4_OSPF_MIB {
            get {
                object obj = ResourceManager.GetObject("ARROWPOINT-IPV4-OSPF-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ATM_TC_MIB {
            get {
                object obj = ResourceManager.GetObject("ATM-TC-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BASEBRDD_MIB_MIB {
            get {
                object obj = ResourceManager.GetObject("BASEBRDD_MIB-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BRIDGE_MIB {
            get {
                object obj = ResourceManager.GetObject("BRIDGE_MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CISCO_AAA_SERVER_MIB {
            get {
                object obj = ResourceManager.GetObject("CISCO-AAA-SERVER-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CISCO_BULK_FILE_MIB {
            get {
                object obj = ResourceManager.GetObject("CISCO-BULK-FILE-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CISCO_CSG_MIB {
            get {
                object obj = ResourceManager.GetObject("CISCO-CSG-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DISMAN_EVENT_MIB {
            get {
                object obj = ResourceManager.GetObject("DISMAN-EVENT-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DISMAN_EXPRESSION_MIB {
            get {
                object obj = ResourceManager.GetObject("DISMAN-EXPRESSION-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DISMAN_NSLOOKUP_MIB {
            get {
                object obj = ResourceManager.GetObject("DISMAN-NSLOOKUP-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DISMAN_PING_MIB {
            get {
                object obj = ResourceManager.GetObject("DISMAN-PING-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DISMAN_SCHEDULE_MIB {
            get {
                object obj = ResourceManager.GetObject("DISMAN-SCHEDULE-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DISMAN_SCRIPT_MIB {
            get {
                object obj = ResourceManager.GetObject("DISMAN-SCRIPT-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DISMAN_TRACEROUTE_MIB {
            get {
                object obj = ResourceManager.GetObject("DISMAN-TRACEROUTE-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DMTF_DMI_MIB {
            get {
                object obj = ResourceManager.GetObject("DMTF-DMI-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EtherLike_MIB {
            get {
                object obj = ResourceManager.GetObject("EtherLike-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fivevarbinds {
            get {
                object obj = ResourceManager.GetObject("fivevarbinds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] get {
            get {
                object obj = ResourceManager.GetObject("get", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] getresponse {
            get {
                object obj = ResourceManager.GetObject("getresponse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HCNUM_TC {
            get {
                object obj = ResourceManager.GetObject("HCNUM-TC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HOST_RESOURCES_MIB {
            get {
                object obj = ResourceManager.GetObject("HOST-RESOURCES-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HOST_RESOURCES_TYPES {
            get {
                object obj = ResourceManager.GetObject("HOST-RESOURCES-TYPES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IANA_ADDRESS_FAMILY_NUMBERS_MIB {
            get {
                object obj = ResourceManager.GetObject("IANA-ADDRESS-FAMILY-NUMBERS-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IANA_LANGUAGE_MIB {
            get {
                object obj = ResourceManager.GetObject("IANA-LANGUAGE-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IANA_RTPROTO_MIB {
            get {
                object obj = ResourceManager.GetObject("IANA-RTPROTO-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IANAifType_MIB {
            get {
                object obj = ResourceManager.GetObject("IANAifType-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IEEE8021_PAE_MIB {
            get {
                object obj = ResourceManager.GetObject("IEEE8021-PAE-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IEEE802DOT11_MIB {
            get {
                object obj = ResourceManager.GetObject("IEEE802DOT11-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IF_INVERTED_STACK_MIB {
            get {
                object obj = ResourceManager.GetObject("IF-INVERTED-STACK-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IF_MIB {
            get {
                object obj = ResourceManager.GetObject("IF-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] INET_ADDRESS_MIB {
            get {
                object obj = ResourceManager.GetObject("INET-ADDRESS-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IP_FORWARD_MIB {
            get {
                object obj = ResourceManager.GetObject("IP-FORWARD-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IP_MIB {
            get {
                object obj = ResourceManager.GetObject("IP-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IPV6_FLOW_LABEL_MIB {
            get {
                object obj = ResourceManager.GetObject("IPV6-FLOW-LABEL-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IPV6_ICMP_MIB {
            get {
                object obj = ResourceManager.GetObject("IPV6-ICMP-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IPV6_MIB {
            get {
                object obj = ResourceManager.GetObject("IPV6-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IPV6_TC {
            get {
                object obj = ResourceManager.GetObject("IPV6-TC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IPV6_TCP_MIB {
            get {
                object obj = ResourceManager.GetObject("IPV6-TCP-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IPV6_UDP_MIB {
            get {
                object obj = ResourceManager.GetObject("IPV6-UDP-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JVM_MANAGEMENT_MIB {
            get {
                object obj = ResourceManager.GetObject("JVM-MANAGEMENT-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LM_SENSORS_MIB {
            get {
                object obj = ResourceManager.GetObject("LM-SENSORS-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MTA_MIB {
            get {
                object obj = ResourceManager.GetObject("MTA-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NET_SNMP_AGENT_MIB {
            get {
                object obj = ResourceManager.GetObject("NET-SNMP-AGENT-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NET_SNMP_EXAMPLES_MIB {
            get {
                object obj = ResourceManager.GetObject("NET-SNMP-EXAMPLES-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NET_SNMP_EXTEND_MIB {
            get {
                object obj = ResourceManager.GetObject("NET-SNMP-EXTEND-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NET_SNMP_MIB {
            get {
                object obj = ResourceManager.GetObject("NET-SNMP-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NET_SNMP_MONITOR_MIB {
            get {
                object obj = ResourceManager.GetObject("NET-SNMP-MONITOR-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NET_SNMP_SYSTEM_MIB {
            get {
                object obj = ResourceManager.GetObject("NET-SNMP-SYSTEM-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NET_SNMP_TC {
            get {
                object obj = ResourceManager.GetObject("NET-SNMP-TC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NET_SNMP_VACM_MIB {
            get {
                object obj = ResourceManager.GetObject("NET-SNMP-VACM-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NETWORK_SERVICES_MIB {
            get {
                object obj = ResourceManager.GetObject("NETWORK-SERVICES-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NOTIFICATION_LOG_MIB {
            get {
                object obj = ResourceManager.GetObject("NOTIFICATION-LOG-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] novarbind {
            get {
                object obj = ResourceManager.GetObject("novarbind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] onevarbind {
            get {
                object obj = ResourceManager.GetObject("onevarbind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RFC_1212 {
            get {
                object obj = ResourceManager.GetObject("RFC-1212", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RFC_1215 {
            get {
                object obj = ResourceManager.GetObject("RFC-1215", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RFC1155_SMI {
            get {
                object obj = ResourceManager.GetObject("RFC1155-SMI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RFC1157_SNMP {
            get {
                object obj = ResourceManager.GetObject("RFC1157-SNMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RFC1213_MIB {
            get {
                object obj = ResourceManager.GetObject("RFC1213-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RFC1213_MIB2 {
            get {
                object obj = ResourceManager.GetObject("RFC1213_MIB2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RFC1271_MIB {
            get {
                object obj = ResourceManager.GetObject("RFC1271-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RMON_MIB {
            get {
                object obj = ResourceManager.GetObject("RMON-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SMUX_MIB {
            get {
                object obj = ResourceManager.GetObject("SMUX-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_COMMUNITY_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-COMMUNITY-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_FRAMEWORK_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-FRAMEWORK-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_MPD_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-MPD-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_NOTIFICATION_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-NOTIFICATION-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_PROXY_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-PROXY-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_TARGET_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-TARGET-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_USER_BASED_SM_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-USER-BASED-SM-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_USM_AES_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-USM-AES-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_USM_DH_OBJECTS_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-USM-DH-OBJECTS-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMP_VIEW_BASED_ACM_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMP-VIEW-BASED-ACM-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMPv2_CONF {
            get {
                object obj = ResourceManager.GetObject("SNMPv2-CONF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMPv2_MIB {
            get {
                object obj = ResourceManager.GetObject("SNMPv2-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMPV2_PDU {
            get {
                object obj = ResourceManager.GetObject("SNMPV2-PDU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMPv2_SMI {
            get {
                object obj = ResourceManager.GetObject("SNMPv2-SMI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMPv2_TC {
            get {
                object obj = ResourceManager.GetObject("SNMPv2-TC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNMPv2_TM {
            get {
                object obj = ResourceManager.GetObject("SNMPv2-TM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SYMMIB_MIB_MIB {
            get {
                object obj = ResourceManager.GetObject("SYMMIB_MIB-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TCP_MIB {
            get {
                object obj = ResourceManager.GetObject("TCP-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TRANSPORT_ADDRESS_MIB {
            get {
                object obj = ResourceManager.GetObject("TRANSPORT-ADDRESS-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TUNNEL_MIB {
            get {
                object obj = ResourceManager.GetObject("TUNNEL-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] twovarbinds {
            get {
                object obj = ResourceManager.GetObject("twovarbinds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UCD_DEMO_MIB {
            get {
                object obj = ResourceManager.GetObject("UCD-DEMO-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UCD_DISKIO_MIB {
            get {
                object obj = ResourceManager.GetObject("UCD-DISKIO-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UCD_DLMOD_MIB {
            get {
                object obj = ResourceManager.GetObject("UCD-DLMOD-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UCD_IPFILTER_MIB {
            get {
                object obj = ResourceManager.GetObject("UCD-IPFILTER-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UCD_IPFWACC_MIB {
            get {
                object obj = ResourceManager.GetObject("UCD-IPFWACC-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UCD_SNMP_MIB {
            get {
                object obj = ResourceManager.GetObject("UCD-SNMP-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UCD_SNMP_MIB_OLD {
            get {
                object obj = ResourceManager.GetObject("UCD-SNMP-MIB-OLD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UDP_MIB {
            get {
                object obj = ResourceManager.GetObject("UDP-MIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
